<?php

namespace Tests\Feature;

use App\Thread;
use App\Trending;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * @property \App\Trending trending
 */
class TrendingTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->trending = new Trending();
        $this->trending->reset();
    }

    /** @test */
    public function it_increments_thread_score_each_time_it_is_read()
    {
        $this->assertEmpty($this->trending->get());

        $thread = factory(Thread::class)->create();

    	$this->get($thread->path());

        $this->assertCount(1, $this->trending->get());
    }
}
